version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: io.ktor:ktor-server-netty
    versions:
    - 1.5.1
    - 1.5.2
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
